source "https://rubygems.org"
ruby "2.5.0"

gem "rails"
gem "thin"
gem "rails_12factor"
gem "devise"
gem "delayed_job"
gem "delayed_job_active_record"
gem "jwt"
gem "mutations"
gem "active_model_serializers"
gem "rack-cors"
gem "rack-attack"
gem "paperclip"
gem "figaro"
gem "fog-google", git: "https://github.com/fog/fog-google"
gem "pg"
gem "polymorphic_constraints"
gem "tzinfo" # For validation of user selected timezone names
gem "foreman"
gem "webpack-rails"
gem "rollbar"
gem "skylight"
gem "bunny"
gem "request_store"
gem "secure_headers"
gem "valid_url"
gem "font-awesome-rails"

group :development, :test do
  gem "hashdiff"
  gem "codecov", require: false
  gem "database_cleaner"
  gem "pry"
  gem "pry-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "smarf_doc", git: "https://github.com/RickCarlino/smarf_doc.git"
  gem "rails-erd"
  gem "rspec"
  gem "rspec-rails"
  gem "simplecov"
  gem "letter_opener"
  gem "capybara"
  gem "selenium-webdriver"
end
