import { SceneObject } from "farmbot/dist/resources/api_resources";

export const OUTDOOR_SCENE_OBJECTS: SceneObject[] = [
  {
    name: "Tree",
    texture: "none",
    shape: "tree",
    color: "#ffffff",
    show: true,
    x_center: 0,
    y_center: 5000,
    z_base: 0,
    x_size: 1000,
    y_size: 1000,
    z_size: 2500,
    x_origin: "home",
    y_origin: "home",
    z_origin: "world",
  },
  {
    name: "Solar Panel",
    texture: "none",
    shape: "solar",
    color: "#ffffff",
    show: true,
    x_center: 2000,
    y_center: 0,
    z_base: 0,
    x_size: 800,
    y_size: 2000,
    z_size: 300,
    x_origin: "max",
    y_origin: "world",
    z_origin: "world",
  },
  {
    name: "Hedge",
    texture: "grass",
    shape: "box",
    color: "#ffffff",
    show: true,
    x_center: 3500,
    y_center: 4500,
    z_base: 0,
    x_size: 5000,
    y_size: 500,
    z_size: 1000,
    x_origin: "home",
    y_origin: "home",
    z_origin: "world",
  },
  {
    name: "Fence",
    texture: "wood",
    shape: "fence",
    color: "#cccccc",
    show: true,
    x_center: -1000,
    y_center: 2000,
    z_base: 0,
    x_size: 0,
    y_size: 5000,
    z_size: 1000,
    x_origin: "home",
    y_origin: "home",
    z_origin: "world",
  },
];
