import type { SceneObject } from "farmbot/dist/resources/api_resources";

export type SceneObjectAxis = "x" | "y" | "z" | "r";

export interface CatalogSceneObject extends SceneObject {
  preserve_axes?: SceneObjectAxis[];
}

export const sceneObjectThumbnailFilename = (name: string) =>
  `${name.toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")}.avif`;

export const DEFAULT_SCENE_OBJECT: SceneObject = {
  name: "",
  texture: "concrete",
  shape: "box",
  color: "#ffffff",
  show: true,
  x_center: 0,
  y_center: 0,
  z_base: 0,
  x_size: 100,
  y_size: 100,
  z_size: 100,
  x_origin: "home",
  y_origin: "home",
  z_origin: "world",
  rotation: 0,
};

export const GREENHOUSE_SCENE_OBJECTS: CatalogSceneObject[] = [
  {
    name: "Greenhouse Wall Y",
    texture: "none",
    shape: "window",
    color: "#f4f4f4",
    show: true,
    x_center: -2150,
    y_center: -2830,
    z_base: 0,
    x_size: 10,
    y_size: 10000,
    z_size: 2500,
    x_origin: "home",
    y_origin: "max",
    z_origin: "world",
    rotation: 0,
    preserve_axes: ["x"],
  },
  {
    name: "Greenhouse Wall X",
    texture: "none",
    shape: "window",
    color: "#f4f4f4",
    show: true,
    x_center: 2850,
    y_center: 2140,
    z_base: 0,
    x_size: 10000,
    y_size: 10,
    z_size: 2500,
    x_origin: "home",
    y_origin: "max",
    z_origin: "world",
    rotation: 0,
    preserve_axes: ["y"],
  },
  {
    name: "Potted Plant",
    texture: "none",
    shape: "plant",
    color: "#ffffff",
    show: true,
    x_center: -1920,
    y_center: 970,
    z_base: 0,
    x_size: 500,
    y_size: 500,
    z_size: 900,
    x_origin: "home",
    y_origin: "max",
    z_origin: "world",
    rotation: 0,
    preserve_axes: ["x", "y", "r"],
  },
  {
    name: "Shelf",
    texture: "wood",
    shape: "box",
    color: "#aaa",
    show: true,
    x_center: 2850,
    y_center: 1840,
    z_base: 775,
    x_size: 10000,
    y_size: 600,
    z_size: 50,
    x_origin: "home",
    y_origin: "max",
    z_origin: "world",
    rotation: 0,
    preserve_axes: ["z"],
  },
  {
    name: "Starter Tray 1",
    texture: "none",
    shape: "tray",
    color: "#ffffff",
    show: true,
    x_center: -150,
    y_center: 1830,
    z_base: 825,
    x_size: 700,
    y_size: 250,
    z_size: 90,
    x_origin: "home",
    y_origin: "max",
    z_origin: "world",
    rotation: 0,
    preserve_axes: ["z"],
  },
  {
    name: "Starter Tray 2",
    texture: "none",
    shape: "tray",
    color: "#ffffff",
    show: true,
    x_center: 850,
    y_center: 1830,
    z_base: 825,
    x_size: 700,
    y_size: 250,
    z_size: 90,
    x_origin: "home",
    y_origin: "max",
    z_origin: "world",
    rotation: 0,
    preserve_axes: ["z"],
  },
];

export const LAB_SCENE_OBJECTS: CatalogSceneObject[] = [
  {
    name: "Wall Y",
    texture: "none",
    shape: "box",
    color: "#f4f4f4",
    show: true,
    x_center: -2250,
    y_center: -2830,
    z_base: 0,
    x_size: 200,
    y_size: 10000,
    z_size: 2500,
    x_origin: "home",
    y_origin: "max",
    z_origin: "world",
    rotation: 0,
    preserve_axes: ["x"],
  },
  {
    name: "Wall X",
    texture: "none",
    shape: "box",
    color: "#f4f4f4",
    show: true,
    x_center: 2750,
    y_center: 2240,
    z_base: 0,
    x_size: 10200,
    y_size: 200,
    z_size: 2500,
    x_origin: "home",
    y_origin: "max",
    z_origin: "world",
    rotation: 0,
    preserve_axes: ["y"],
  },
  {
    name: "Lower Shelf",
    texture: "wood",
    shape: "box",
    color: "#999",
    show: true,
    x_center: 2850,
    y_center: 2040,
    z_base: 810,
    x_size: 10000,
    y_size: 200,
    z_size: 50,
    x_origin: "home",
    y_origin: "max",
    z_origin: "world",
    rotation: 0,
    preserve_axes: ["z"],
  },
  {
    name: "Upper Shelf",
    texture: "wood",
    shape: "box",
    color: "#999",
    show: true,
    x_center: 2850,
    y_center: 2040,
    z_base: 1230,
    x_size: 10000,
    y_size: 200,
    z_size: 50,
    x_origin: "home",
    y_origin: "max",
    z_origin: "world",
    rotation: 0,
    preserve_axes: ["z"]
  },
  {
    name: "Desk",
    texture: "wood",
    shape: "desk",
    color: "#666",
    show: true,
    x_center: 850,
    y_center: 0,
    z_base: 0,
    x_size: 500,
    y_size: 1000,
    z_size: 600,
    x_origin: "max",
    y_origin: "world",
    z_origin: "world",
    rotation: 0,
    preserve_axes: ["x"],
  },
  {
    name: "Laptop",
    texture: "none",
    shape: "laptop",
    color: "#fff",
    show: true,
    x_center: 800,
    y_center: 0,
    z_base: 600,
    x_size: 300,
    y_size: 300,
    z_size: 200,
    x_origin: "max",
    y_origin: "world",
    z_origin: "world",
    rotation: 0,
    preserve_axes: ["x", "y", "z"],
  },
];

export const OUTDOOR_SCENE_OBJECTS: CatalogSceneObject[] = [
  {
    name: "Tree",
    texture: "none",
    shape: "tree",
    color: "#ffffff",
    show: true,
    x_center: 0,
    y_center: 2040,
    z_base: 0,
    x_size: 1000,
    y_size: 1000,
    z_size: 2500,
    x_origin: "home",
    y_origin: "max",
    z_origin: "world",
    rotation: 0,
    preserve_axes: ["x", "y", "r"],
  },
  {
    name: "Solar Panel",
    texture: "none",
    shape: "solar",
    color: "#ffffff",
    show: true,
    x_center: 2000,
    y_center: 0,
    z_base: 0,
    x_size: 500,
    y_size: 2000,
    z_size: 300,
    x_origin: "max",
    y_origin: "world",
    z_origin: "world",
    rotation: 0,
    preserve_axes: ["x"],
  },
  {
    name: "Hedge",
    texture: "grass",
    shape: "box",
    color: "#ffffff",
    show: true,
    x_center: 3500,
    y_center: 2040,
    z_base: 0,
    x_size: 5000,
    y_size: 500,
    z_size: 1000,
    x_origin: "home",
    y_origin: "max",
    z_origin: "world",
    rotation: 0,
    preserve_axes: ["y"],
  },
  {
    name: "Fence",
    texture: "wood",
    shape: "fence",
    color: "#cccccc",
    show: true,
    x_center: -1500,
    y_center: -500,
    z_base: 0,
    x_size: 10,
    y_size: 5000,
    z_size: 1000,
    x_origin: "home",
    y_origin: "max",
    z_origin: "world",
    rotation: 0,
    preserve_axes: ["x"],
  },
];

export const MARS_SCENE_OBJECTS: CatalogSceneObject[] = [
  {
    name: "Astronaut",
    texture: "none",
    shape: "astronaut",
    color: "#f66151",
    show: true,
    x_center: 1000,
    y_center: 1000,
    z_base: 0,
    x_size: 900,
    y_size: 600,
    z_size: 1900,
    x_origin: "max",
    y_origin: "max",
    z_origin: "world",
    rotation: 0,
    preserve_axes: ["x", "y"],
  },
  {
    name: "Rover",
    texture: "none",
    shape: "rover",
    color: "#ffffff",
    show: true,
    x_center: -3800,
    y_center: 6600,
    z_base: 0,
    x_size: 4600,
    y_size: 3000,
    z_size: 2500,
    x_origin: "home",
    y_origin: "home",
    z_origin: "world",
    rotation: 0,
    preserve_axes: ["x", "y"],
  },
  {
    name: "Hab",
    texture: "none",
    shape: "hab",
    color: "#aaa",
    show: true,
    x_center: 3000,
    y_center: 9000,
    z_base: 0,
    x_size: 6000,
    y_size: 4000,
    z_size: 3000,
    x_origin: "home",
    y_origin: "home",
    z_origin: "world",
    rotation: 0,
    preserve_axes: ["y", "z"],
  },
];

export const SCENE_OBJECT_CATALOG_SCENES = {
  greenhouse: GREENHOUSE_SCENE_OBJECTS
    .filter(sceneObject => ![
      "Starter Tray 2",
      "Greenhouse Wall Y",
    ].includes(sceneObject.name))
    .map(sceneObject => sceneObject.name == "Starter Tray 1"
      ? { ...sceneObject, name: "Starter Tray" }
      : sceneObject)
    .map(sceneObject => sceneObject.name == "Greenhouse Wall X"
      ? { ...sceneObject, name: "Greenhouse Wall" }
      : sceneObject),
  lab: LAB_SCENE_OBJECTS.filter(sceneObject =>
    ![
      "Lower Shelf",
      "Upper Shelf",
      "Wall Y",
    ].includes(sceneObject.name))
    .map(sceneObject => sceneObject.name == "Wall X"
      ? { ...sceneObject, name: "Wall" }
      : sceneObject),
  outdoor: OUTDOOR_SCENE_OBJECTS,
  mars: MARS_SCENE_OBJECTS,
};
