// Generated by generate_plant_icon_atlas.ts. Do not edit manually.
/* eslint-disable max-len */

export const PROMO_PLANT_ICON_ATLAS_URL = "/crops/icons/promo-atlas.avif";
export const PROMO_PLANT_ICON_ATLAS_TEXTURE_WIDTH = 3500;
export const PROMO_PLANT_ICON_ATLAS_TEXTURE_HEIGHT = 3000;
export const PROMO_PLANT_ICON_ATLAS_CELL_WIDTH = 500;
export const PROMO_PLANT_ICON_ATLAS_CELL_HEIGHT = 500;
export const PROMO_PLANT_ICON_ATLAS_COLUMNS = 7;
export const PROMO_PLANT_ICON_ATLAS_ICON_SLUGS = "anaheim-pepper,arugula,basil,beet,bibb-lettuce,bok-choy,broccoli,brussels-sprout,carrot,cauliflower,celery,cilantro,collard-greens,cucumber,eggplant,french-breakfast-radish,garlic,generic-plant,golden-beet,hillbilly-tomato,icicle-radish,lavender,leek,napa-cabbage,okra,parsnip,rainbow-chard,red-bell-pepper,red-curly-kale,red-russian-kale,runner-bean,rutabaga,savoy-cabbage,shallot,snap-pea,spinach,sweet-potato,swiss-chard,turmeric,turnip,yellow-onion,zucchini";

export const PROMO_PLANT_ICON_ATLAS_FRAMES = [] as const;
