#!/usr/bin/env python3
import json
import sys

with open(sys.argv[1], encoding="utf-8") as f:
    entries = json.load(f)

for entry in entries:
    actions = entry.get("actions", [])
    roi = entry.get("roi", {})
    print("\034".join([
        entry["name"],
        entry["mode"],
        entry["url"],
        json.dumps(actions, separators=(",", ":")) if actions else "",
        entry.get("state", ""),
        json.dumps(roi, separators=(",", ":")) if roi else "",
    ]))
