#!/usr/bin/env python3
import csv
import os
from pathlib import Path
import subprocess


fps_history = os.environ["FPS_HISTORY"]
fps_value = os.environ["FPS_VALUE"]
commit_sha = os.environ["GITHUB_SHA"][:10]
github_env = os.environ["GITHUB_ENV"]
csv_path = Path("/tmp") / f"{fps_history}.csv"
csv_header = ["fps", "% change", "commit sha"]

previous = subprocess.check_output(
    ["scripts/ci/previous-fps-value"],
    text=True,
).strip()
print(f"Previous value: {previous} fps")

percent_change = subprocess.check_output([
    "scripts/ci/percent-change",
    "--new",
    fps_value,
    "--old",
    previous,
], text=True).strip()
print(f"{fps_value} fps ({percent_change}% change)")

with open(github_env, "a") as env_file:
    env_file.write(f"PERCENT_CHANGE={percent_change}\n")

if not csv_path.exists():
    csv_path.write_text(",".join(csv_header) + "\n")

with csv_path.open("a", newline="") as csv_file:
    writer = csv.writer(csv_file)
    writer.writerow([fps_value, percent_change, commit_sha])
