import { Crops } from "../crops/interfaces";

export const FAKE_CROPS: Crops = {
  "mint": {
    name: "Mint",
    binomial_name: "Mentha spicata",
    common_names: ["Mint", "spearmint"],
    description: "Mint is a perennial herb with a distinctive taste.",
    sun_requirements: "Partial sun",
    sowing_method: "Direct seed indoors or outside",
    spread: 100,
    row_spacing: 100,
    height: 60,
    growing_degree_days: 100,
    companions: ["strawberry"],
    image: "/crops/images/mint.jpg",
    icon: "/crops/icons/mint.avif"
  },
  "strawberry": {
    name: "Strawberry",
    binomial_name: "",
    common_names: [],
    description: "",
    sun_requirements: "",
    sowing_method: "",
    spread: 25,
    row_spacing: 35,
    height: 60,
    growing_degree_days: 100,
    companions: [],
    icon: "",
    image: "",
  },
  "generic-plant": {
    name: "",
    binomial_name: "",
    common_names: [],
    description: "",
    sun_requirements: "",
    sowing_method: "",
    spread: 0,
    row_spacing: 0,
    height: 0,
    growing_degree_days: 0,
    companions: [],
    icon: "",
    image: "",
  },
};
