class CreateConfigTables < ActiveRecord::Migration[5.1]
  def change
    create_table :firmware_config do |t|
      t.float :encoder_enabled_x,                 default: -99
      t.float :encoder_enabled_y,                 default: -99
      t.float :encoder_enabled_z,                 default: -99
      t.float :encoder_invert_x,                  default: -99
      t.float :encoder_invert_y,                  default: -99
      t.float :encoder_invert_z,                  default: -99
      t.float :encoder_missed_steps_decay_x,      default: -99
      t.float :encoder_missed_steps_decay_y,      default: -99
      t.float :encoder_missed_steps_decay_z,      default: -99
      t.float :encoder_missed_steps_max_x,        default: -99
      t.float :encoder_missed_steps_max_y,        default: -99
      t.float :encoder_missed_steps_max_z,        default: -99
      t.float :encoder_scaling_x,                 default: -99
      t.float :encoder_scaling_y,                 default: -99
      t.float :encoder_scaling_z,                 default: -99
      t.float :encoder_type_x,                    default: -99
      t.float :encoder_type_y,                    default: -99
      t.float :encoder_type_z,                    default: -99
      t.float :encoder_use_for_pos_x,             default: -99
      t.float :encoder_use_for_pos_y,             default: -99
      t.float :encoder_use_for_pos_z,             default: -99
      t.float :movement_axis_nr_steps_x,          default: -99
      t.float :movement_axis_nr_steps_y,          default: -99
      t.float :movement_axis_nr_steps_z,          default: -99
      t.float :movement_enable_endpoints_x,       default: -99
      t.float :movement_enable_endpoints_y,       default: -99
      t.float :movement_enable_endpoints_z,       default: -99
      t.float :movement_home_at_boot_x,           default: -99
      t.float :movement_home_at_boot_y,           default: -99
      t.float :movement_home_at_boot_z,           default: -99
      t.float :movement_home_spd_x,               default: -99
      t.float :movement_home_spd_y,               default: -99
      t.float :movement_home_spd_z,               default: -99
      t.float :movement_home_up_x,                default: -99
      t.float :movement_home_up_y,                default: -99
      t.float :movement_home_up_z,                default: -99
      t.float :movement_invert_endpoints_x,       default: -99
      t.float :movement_invert_endpoints_y,       default: -99
      t.float :movement_invert_endpoints_z,       default: -99
      t.float :movement_invert_motor_x,           default: -99
      t.float :movement_invert_motor_y,           default: -99
      t.float :movement_invert_motor_z,           default: -99
      t.float :movement_keep_active_x,            default: -99
      t.float :movement_keep_active_y,            default: -99
      t.float :movement_keep_active_z,            default: -99
      t.float :movement_max_spd_x,                default: -99
      t.float :movement_max_spd_y,                default: -99
      t.float :movement_max_spd_z,                default: -99
      t.float :movement_min_spd_x,                default: -99
      t.float :movement_min_spd_y,                default: -99
      t.float :movement_min_spd_z,                default: -99
      t.float :movement_secondary_motor_invert_x, default: -99
      t.float :movement_secondary_motor_x,        default: -99
      t.float :movement_step_per_mm_x,            default: -99
      t.float :movement_step_per_mm_y,            default: -99
      t.float :movement_step_per_mm_z,            default: -99
      t.float :movement_steps_acc_dec_x,          default: -99
      t.float :movement_steps_acc_dec_y,          default: -99
      t.float :movement_steps_acc_dec_z,          default: -99
      t.float :movement_stop_at_home_x,           default: -99
      t.float :movement_stop_at_home_y,           default: -99
      t.float :movement_stop_at_home_z,           default: -99
      t.float :movement_stop_at_max_x,            default: -99
      t.float :movement_stop_at_max_y,            default: -99
      t.float :movement_stop_at_max_z,            default: -99
      t.float :movement_timeout_x,                default: -99
      t.float :movement_timeout_y,                default: -99
      t.float :movement_timeout_z,                default: -99
      t.float :param_e_stop_on_mov_err,           default: -99
      t.float :param_mov_nr_retry,                default: -99
      t.float :param_version,                     default: -99
      t.float :pin_guard_1_active_state,          default: -99
      t.float :pin_guard_1_pin_nr,                default: -99
      t.float :pin_guard_1_time_out,              default: -99
      t.float :pin_guard_2_active_state,          default: -99
      t.float :pin_guard_2_pin_nr,                default: -99
      t.float :pin_guard_2_time_out,              default: -99
      t.float :pin_guard_3_active_state,          default: -99
      t.float :pin_guard_3_pin_nr,                default: -99
      t.float :pin_guard_3_time_out,              default: -99
      t.float :pin_guard_4_active_state,          default: -99
      t.float :pin_guard_4_pin_nr,                default: -99
      t.float :pin_guard_4_time_out,              default: -99
      t.float :pin_guard_5_active_state,          default: -99
      t.float :pin_guard_5_pin_nr,                default: -99
      t.float :pin_guard_5_time_out,              default: -99
    end

    create_table :web_app_config do |t|
      t.references :device
      t.boolean :confirm_step_deletion,  default: false
      t.boolean :disable_animations,     default: false
      t.boolean :disable_i18n,           default: false
      t.boolean :display_trail,          default: false
      t.boolean :dynamic_map,            default: false
      t.boolean :encoder_figure,         default: false
      t.boolean :hide_webcam_widget,     default: false
      t.boolean :legend_menu_open,       default: false
      t.boolean :map_xl,                 default: false
      t.boolean :raw_encoders,           default: false
      t.boolean :scaled_encoders,        default: false
      t.boolean :show_farmbot,           default: false
      t.boolean :show_plants,            default: false
      t.boolean :show_points,            default: false
      t.boolean :show_spread,            default: false
      t.boolean :weed_detector,          default: false
      t.boolean :x_axis_inverted,        default: false
      t.boolean :y_axis_inverted,        default: false
      t.boolean :z_axis_inverted,        default: false
      t.integer :bot_origin_quadrant,    default: -99
      t.integer :zoom_level,             default: -99
      t.integer :success_log,            default: -99
      t.integer :busy_log,               default: -99
      t.integer :warn_log,               default: -99
      t.integer :error_log,              default: -99
      t.integer :info_log,               default: -99
      t.integer :fun_log,                default: -99
      t.integer :debug_log,              default: -99
      t.integer :successs_log,           default: -99
    end

    create_table :fbos_config do |t|
      t.boolean :auto_sync,                 default: false
      t.boolean :disable_factory_reset,     default: false
      t.boolean :firmware_input_log,        default: false
      t.boolean :firmware_output_log,       default: false
      t.boolean :sequence_body_log,         default: false
      t.boolean :sequence_complete_log,     default: false
      t.boolean :sequence_init_log,         default: false
      t.string :firmware_hardware, default: default: "arduino"
      t.integer :arduino_debug_messages,    default: -99
      t.integer :fw_auto_update,            default: -99
      t.integer :os_auto_update,            default: -99
      t.integer :network_not_found_timer
    end
  end
end
