import {
  mkdtempSync, mkdirSync, readdirSync, rmSync, writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { basename, dirname, extname, join, resolve } from "node:path";
import { execFileSync } from "node:child_process";

export interface IconSize {
  iconUrl: string;
  filePath: string;
  width: number;
  height: number;
}

export interface AtlasFrame {
  iconUrl: string;
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface AtlasLayout {
  cellWidth: number;
  cellHeight: number;
  columns: number;
  rows: number;
  textureWidth: number;
  textureHeight: number;
  frames: AtlasFrame[];
}

const ROOT = process.cwd();
const ICON_DIR = resolve(ROOT, "public/crops/icons");

interface AtlasConfig {
  url: string;
  moduleOutput: string;
  exportPrefix: string;
  iconUrls?: string[];
}

const FULL_ATLAS: AtlasConfig = {
  url: "/crops/icons/atlas.avif",
  moduleOutput: "frontend/three_d_garden/garden/generated_plant_icon_atlas.ts",
  exportPrefix: "PLANT_ICON_ATLAS",
};

const PROMO_ICON_SLUGS = [
  "anaheim-pepper", "arugula", "basil", "beet", "bibb-lettuce", "bok-choy",
  "broccoli", "brussels-sprout", "carrot", "cauliflower", "celery",
  "cilantro", "collard-greens", "cucumber", "eggplant",
  "french-breakfast-radish", "garlic", "generic-plant", "golden-beet",
  "hillbilly-tomato", "icicle-radish", "lavender", "leek", "napa-cabbage",
  "okra", "parsnip", "rainbow-chard", "red-bell-pepper", "red-curly-kale",
  "red-russian-kale", "runner-bean", "rutabaga", "savoy-cabbage", "shallot",
  "snap-pea", "spinach", "sweet-potato", "swiss-chard", "turmeric", "turnip",
  "yellow-onion", "zucchini",
];

const PROMO_ATLAS: AtlasConfig = {
  url: "/crops/icons/promo-atlas.avif",
  moduleOutput:
    "frontend/three_d_garden/garden/generated_promo_plant_icon_atlas.ts",
  exportPrefix: "PROMO_PLANT_ICON_ATLAS",
  iconUrls: PROMO_ICON_SLUGS.map(slug => `/crops/icons/${slug}.avif`),
};

const ATLAS_CONFIGS = [FULL_ATLAS, PROMO_ATLAS];
const atlasOutput = (atlas: AtlasConfig) =>
  resolve(ROOT, "public", atlas.url.slice(1));
const moduleOutput = (atlas: AtlasConfig) =>
  resolve(ROOT, atlas.moduleOutput);
const generatedAtlasFileNames = () =>
  ATLAS_CONFIGS.map(atlas => basename(atlasOutput(atlas)));

const generatedHeader =
  "// Generated by generate_plant_icon_atlas.ts. Do not edit manually.\n"
  + "/* eslint-disable max-len */";

export const getAtlasLayout = (icons: IconSize[]): AtlasLayout => {
  if (!icons.length) {
    throw new Error("No crop icons found.");
  }

  const cellWidth = Math.max(...icons.map(icon => icon.width));
  const cellHeight = Math.max(...icons.map(icon => icon.height));
  const columns = Math.ceil(Math.sqrt(icons.length));
  const rows = Math.ceil(icons.length / columns);
  const textureWidth = columns * cellWidth;
  const textureHeight = rows * cellHeight;
  const frames = icons.map((icon, index) => ({
    iconUrl: icon.iconUrl,
    x: (index % columns) * cellWidth,
    y: Math.floor(index / columns) * cellHeight,
    width: icon.width,
    height: icon.height,
  }));

  return {
    cellWidth,
    cellHeight,
    columns,
    rows,
    textureWidth,
    textureHeight,
    frames,
  };
};

export const formatAtlasModule = (layout: AtlasLayout, atlas: AtlasConfig) => {
  const uniformGrid = layout.frames.every((frame, index) =>
    frame.x == (index % layout.columns) * layout.cellWidth
    && frame.y == Math.floor(index / layout.columns) * layout.cellHeight
    && frame.width == layout.cellWidth
    && frame.height == layout.cellHeight);

  if (uniformGrid) {
    const slugs = layout.frames.map(frame =>
      basename(frame.iconUrl, ".avif"));
    return `${generatedHeader}

export const ${atlas.exportPrefix}_URL = "${atlas.url}";
export const ${atlas.exportPrefix}_TEXTURE_WIDTH = ${layout.textureWidth};
export const ${atlas.exportPrefix}_TEXTURE_HEIGHT = ${layout.textureHeight};
export const ${atlas.exportPrefix}_CELL_WIDTH = ${layout.cellWidth};
export const ${atlas.exportPrefix}_CELL_HEIGHT = ${layout.cellHeight};
export const ${atlas.exportPrefix}_COLUMNS = ${layout.columns};
export const ${atlas.exportPrefix}_ICON_SLUGS = "${slugs.join(",")}";

export const ${atlas.exportPrefix}_FRAMES = [] as const;
`;
  }

  const entries = layout.frames.map(frame =>
    `  ["${frame.iconUrl}", ${frame.x}, ${frame.y}, `
    + `${frame.width}, ${frame.height}],`);

  return `${generatedHeader}

export const ${atlas.exportPrefix}_URL = "${atlas.url}";
export const ${atlas.exportPrefix}_TEXTURE_WIDTH = ${layout.textureWidth};
export const ${atlas.exportPrefix}_TEXTURE_HEIGHT = ${layout.textureHeight};
export const ${atlas.exportPrefix}_CELL_WIDTH = 0;
export const ${atlas.exportPrefix}_CELL_HEIGHT = 0;
export const ${atlas.exportPrefix}_COLUMNS = 0;
export const ${atlas.exportPrefix}_ICON_SLUGS = "";

export const ${atlas.exportPrefix}_FRAMES = [
${entries.join("\n")}
] as const;
`;
};

const getIconFilePaths = (atlas: AtlasConfig) => {
  if (atlas.iconUrls) {
    return atlas.iconUrls.map(iconUrl => resolve(ROOT, "public",
      iconUrl.slice(1)));
  }
  const generatedFiles = new Set(generatedAtlasFileNames());
  return readdirSync(ICON_DIR)
    .filter(file =>
      extname(file) == ".avif" &&
      !generatedFiles.has(file))
    .sort()
    .map(file => resolve(ICON_DIR, file));
};

const identifyIcons = (filePaths: string[]): IconSize[] => {
  const output = execFileSync("magick", [
    "identify",
    "-format",
    "%w\t%h\t%f\n",
    ...filePaths,
  ], { encoding: "utf-8" });

  const sizes = new Map(output.trim().split("\n").map(line => {
    const [width, height, fileName] = line.split("\t");
    return [fileName, {
      width: parseInt(width || "0", 10),
      height: parseInt(height || "0", 10),
    }];
  }));

  return filePaths.map(filePath => {
    const fileName = basename(filePath);
    const size = sizes.get(fileName);
    if (!size) {
      throw new Error(`Unable to identify icon size: ${fileName}`);
    }
    return {
      iconUrl: `/crops/icons/${fileName}`,
      filePath,
      width: size.width,
      height: size.height,
    };
  });
};

const padIcons = (icons: IconSize[], layout: AtlasLayout, tempDir: string) =>
  icons.map(icon => {
    const paddedPath = join(tempDir, basename(icon.filePath, ".avif") + ".png");
    execFileSync("magick", [
      icon.filePath,
      "-background",
      "none",
      "-gravity",
      "northwest",
      "-extent",
      `${layout.cellWidth}x${layout.cellHeight}`,
      paddedPath,
    ], { stdio: "inherit" });
    return paddedPath;
  });

const renderAtlas = (
  paddedPaths: string[],
  layout: AtlasLayout,
  output: string,
) => {
  mkdirSync(dirname(output), { recursive: true });
  execFileSync("magick", [
    "montage",
    ...paddedPaths,
    "-background",
    "none",
    "-tile",
    `${layout.columns}x${layout.rows}`,
    "-geometry",
    `${layout.cellWidth}x${layout.cellHeight}+0+0`,
    "-quality",
    "75",
    output,
  ], { stdio: "inherit" });
};

export const generatePlantIconAtlas = (atlas: AtlasConfig = FULL_ATLAS) => {
  const filePaths = getIconFilePaths(atlas);
  const icons = identifyIcons(filePaths);
  const layout = getAtlasLayout(icons);
  const tempDir = mkdtempSync(join(tmpdir(), "plant-icon-atlas-"));

  try {
    const paddedPaths = padIcons(icons, layout, tempDir);
    renderAtlas(paddedPaths, layout, atlasOutput(atlas));
    writeFileSync(moduleOutput(atlas), formatAtlasModule(layout, atlas));
  } finally {
    rmSync(tempDir, { recursive: true, force: true });
  }
};

export const generatePlantIconAtlases = () => {
  ATLAS_CONFIGS.forEach(generatePlantIconAtlas);
};

if (import.meta.main) {
  generatePlantIconAtlases();
}
