/** THIS INTERFACE IS AUTO-GENERATED BY A SCRIPT.
    DO NOT MANUALLY MODIFY, CHANGES WILL BE
    OVERWRITTEN WHEN DATABASE SCHEMA CHANGES

    If you do need to change this file, first write a database migration,
      then run `rake typescript:interfaces` */

export interface FbosConfig {
  id: number;
  device_id: number;
  created_at: string;
  updated_at: string;
  auto_sync: boolean;
  beta_opt_in: boolean;
  disable_factory_reset: boolean;
  firmware_input_log: boolean;
  firmware_output_log: boolean;
  sequence_body_log: boolean;
  sequence_complete_log: boolean;
  sequence_init_log: boolean;
  arduino_debug_messages: number;
  network_not_found_timer: number;
  os_auto_update: number;
  firmware_hardware: string;
}

export type NumberConfigKey = "id"
    |"device_id"
    |"arduino_debug_messages"
    |"network_not_found_timer"
    |"os_auto_update";

export type StringConfigKey = "created_at"
    |"updated_at"
    |"firmware_hardware";

export type BooleanConfigKey = "auto_sync"
    |"beta_opt_in"
    |"disable_factory_reset"
    |"firmware_input_log"
    |"firmware_output_log"
    |"sequence_body_log"
    |"sequence_complete_log"
    |"sequence_init_log";
