export interface CropMetadata {
  name: string;
  spread: number;
  icon: string;
  companions: string[];
}

const GENERIC_PLANT_ICON = "/crops/icons/generic-plant.avif";

const CROP_ROWS: [string, string, number, string, string[]][] = [
  [
    "acorn-squash",
    "Acorn Squash",
    150,
    "/crops/icons/acorn-squash.avif",
    [
      "borage",
      "corn",
    ],
  ],
  [
    "adjuma-pepper",
    "Adjuma Pepper",
    40,
    "/crops/icons/adjuma-pepper.avif",
    [],
  ],
  [
    "aji-dulce-pepper",
    "Ají Dulce Pepper",
    0,
    "/crops/icons/aji-dulce-pepper.avif",
    [],
  ],
  [
    "aleppo-pepper",
    "Aleppo Pepper",
    0,
    "/crops/icons/aleppo-pepper.avif",
    [],
  ],
  [
    "almond",
    "Almond",
    0,
    "/crops/icons/almond.avif",
    [],
  ],
  [
    "anaheim-pepper",
    "Anaheim Pepper",
    40,
    "/crops/icons/anaheim-pepper.avif",
    [
      "tomato",
    ],
  ],
  [
    "apple",
    "Apple",
    500,
    "/crops/icons/apple.avif",
    [],
  ],
  [
    "apricot",
    "Apricot",
    450,
    "/crops/icons/apricot.avif",
    [],
  ],
  [
    "artichoke",
    "Artichoke",
    120,
    "/crops/icons/artichoke.avif",
    [],
  ],
  [
    "arugula",
    "Arugula",
    20,
    "/crops/icons/arugula.avif",
    [],
  ],
  [
    "asian-pear",
    "Asian Pear",
    600,
    "/crops/icons/asian-pear.avif",
    [
      "borage",
    ],
  ],
  [
    "asparagus",
    "Asparagus",
    42,
    "/crops/icons/asparagus.avif",
    [],
  ],
  [
    "banana-pepper",
    "Banana Pepper",
    30,
    "/crops/icons/banana-pepper.avif",
    [],
  ],
  [
    "barley",
    "Barley",
    0,
    "/crops/icons/barley.avif",
    [],
  ],
  [
    "basil",
    "Basil",
    40,
    "/crops/icons/basil.avif",
    [],
  ],
  [
    "beet",
    "Beet",
    8,
    "/crops/icons/beet.avif",
    [],
  ],
  [
    "belgian-endive",
    "Belgian Endive",
    0,
    "/crops/icons/belgian-endive.avif",
    [],
  ],
  [
    "bibb-lettuce",
    "Bibb Lettuce",
    30,
    "/crops/icons/bibb-lettuce.avif",
    [],
  ],
  [
    "bing-cherry",
    "Bing Cherry",
    760,
    "/crops/icons/bing-cherry.avif",
    [
      "dill",
    ],
  ],
  [
    "birds-eye-chili",
    "Bird's Eye Chili",
    0,
    "/crops/icons/birds-eye-chili.avif",
    [],
  ],
  [
    "bishops-crown-pepper",
    "Bishop's Crown Pepper",
    0,
    "/crops/icons/bishops-crown-pepper.avif",
    [],
  ],
  [
    "black-habanero",
    "Black Habanero",
    40,
    "/crops/icons/black-habanero.avif",
    [
      "spinach",
      "tomato",
    ],
  ],
  [
    "black-prince-tomato",
    "Black Prince Tomato",
    0,
    "/crops/icons/black-prince-tomato.avif",
    [],
  ],
  [
    "black-salsify",
    "Black Salsify",
    0,
    "/crops/icons/black-salsify.avif",
    [
      "carrot",
    ],
  ],
  [
    "blackberry",
    "Blackberry",
    75,
    "/crops/icons/blackberry.avif",
    [],
  ],
  [
    "blue-lake-bean",
    "Blue Lake Bean",
    25,
    "/crops/icons/blue-lake-bean.avif",
    [],
  ],
  [
    "blue-oyster-mushroom",
    "Blue Oyster Mushroom",
    0,
    "/crops/icons/blue-oyster-mushroom.avif",
    [],
  ],
  [
    "blueberry",
    "Blueberry",
    150,
    "/crops/icons/blueberry.avif",
    [],
  ],
  [
    "bok-choy",
    "Bok Choy",
    20,
    "/crops/icons/bok-choy.avif",
    [],
  ],
  [
    "borage",
    "Borage",
    50,
    "/crops/icons/borage.avif",
    [],
  ],
  [
    "brazilian-starfish-pepper",
    "Brazilian Starfish Pepper",
    0,
    "/crops/icons/brazilian-starfish-pepper.avif",
    [],
  ],
  [
    "broccoli",
    "Broccoli",
    60,
    "/crops/icons/broccoli.avif",
    [],
  ],
  [
    "brussels-sprout",
    "Brussels Sprouts",
    80,
    "/crops/icons/brussels-sprout.avif",
    [],
  ],
  [
    "butternut-squash",
    "Butternut Squash",
    150,
    "/crops/icons/butternut-squash.avif",
    [
      "borage",
      "carrot",
    ],
  ],
  [
    "california-poppy",
    "California Poppy",
    0,
    "/crops/icons/california-poppy.avif",
    [],
  ],
  [
    "cannabis",
    "Cannabis",
    0,
    "/crops/icons/cannabis.avif",
    [
      "lemon-balm",
    ],
  ],
  [
    "cantaloupe",
    "Cantaloupe",
    150,
    "/crops/icons/cantaloupe.avif",
    [],
  ],
  [
    "carrot",
    "Carrot",
    10,
    "/crops/icons/carrot.avif",
    [],
  ],
  [
    "cascabel-chili",
    "Cascabel Chili",
    0,
    "/crops/icons/cascabel-chili.avif",
    [
      "spinach",
    ],
  ],
  [
    "cauliflower",
    "Cauliflower",
    30,
    "/crops/icons/cauliflower.avif",
    [
      "dill",
    ],
  ],
  [
    "cayenne-pepper",
    "Cayenne Pepper",
    60,
    "/crops/icons/cayenne-pepper.avif",
    [],
  ],
  [
    "celeriac-root",
    "Celeriac",
    60,
    "/crops/icons/celeriac-root.avif",
    [],
  ],
  [
    "celery",
    "Celery",
    25,
    "/crops/icons/celery.avif",
    [
      "red-cabbage",
    ],
  ],
  [
    "chamomile",
    "Chamomile",
    0,
    "/crops/icons/chamomile.avif",
    [],
  ],
  [
    "chantrelle-mushroom",
    "Chantrelle Mushroom",
    0,
    "/crops/icons/chantrelle-mushroom.avif",
    [],
  ],
  [
    "cheongyang-pepper",
    "Cheongyang Chili Pepper",
    0,
    "/crops/icons/cheongyang-pepper.avif",
    [],
  ],
  [
    "cherokee-purple-tomato",
    "Cherokee Purple Tomato",
    45,
    "/crops/icons/cherokee-purple-tomato.avif",
    [],
  ],
  [
    "cherry-belle-radish",
    "Cherry Belle Radish",
    15,
    "/crops/icons/cherry-belle-radish.avif",
    [],
  ],
  [
    "cherry-stuffer-pepper",
    "Cherry Stuffer Pepper",
    70,
    "/crops/icons/cherry-stuffer-pepper.avif",
    [],
  ],
  [
    "cherry-tomato",
    "Cherry Tomato",
    0,
    "/crops/icons/cherry-tomato.avif",
    [],
  ],
  [
    "chile-de-aborol-pepper",
    "Chile De Aborol",
    0,
    "/crops/icons/chile-de-aborol-pepper.avif",
    [],
  ],
  [
    "cilantro",
    "Cilantro",
    30,
    "/crops/icons/cilantro.avif",
    [],
  ],
  [
    "cinnamon-cap-mushroom",
    "Cinnamon Cap Mushroom",
    0,
    "/crops/icons/cinnamon-cap-mushroom.avif",
    [],
  ],
  [
    "claytonia",
    "Claytonia",
    0,
    "/crops/icons/claytonia.avif",
    [],
  ],
  [
    "collard-greens",
    "Collard Greens",
    30,
    "/crops/icons/collard-greens.avif",
    [],
  ],
  [
    "corn",
    "Corn",
    50,
    "/crops/icons/corn.avif",
    [],
  ],
  [
    "cotton",
    "Cotton",
    0,
    "/crops/icons/cotton.avif",
    [],
  ],
  [
    "cremini-mushroom",
    "Cremini Mushroom",
    0,
    "/crops/icons/cremini-mushroom.avif",
    [],
  ],
  [
    "cubanelle-pepper",
    "Cubanelle Pepper",
    75,
    "/crops/icons/cubanelle-pepper.avif",
    [
      "parsley",
    ],
  ],
  [
    "cucumber",
    "Cucumber",
    0,
    "/crops/icons/cucumber.avif",
    [],
  ],
  [
    "curly-endive",
    "Endive",
    25,
    "/crops/icons/curly-endive.avif",
    [],
  ],
  [
    "curly-kale",
    "Curly Kale",
    0,
    "/crops/icons/curly-kale.avif",
    [],
  ],
  [
    "dandelion",
    "Dandelion",
    45,
    "/crops/icons/dandelion.avif",
    [],
  ],
  [
    "dark-opal-basil",
    "Dark Opal Basil",
    40,
    "/crops/icons/dark-opal-basil.avif",
    [],
  ],
  [
    "datil-pepper",
    "Datil Pepper",
    0,
    "/crops/icons/datil-pepper.avif",
    [
      "carrot",
    ],
  ],
  [
    "delicata-squash",
    "Delicata Squash",
    80,
    "/crops/icons/delicata-squash.avif",
    [
      "icicle-radish",
    ],
  ],
  [
    "diablito-pepper",
    "Diablito Pepper",
    60,
    "/crops/icons/diablito-pepper.avif",
    [],
  ],
  [
    "dill",
    "Dill",
    30,
    "/crops/icons/dill.avif",
    [],
  ],
  [
    "dundicut-pepper",
    "Dundicut",
    0,
    "/crops/icons/dundicut-pepper.avif",
    [
      "eggplant",
    ],
  ],
  [
    "echinacea",
    "Coneflower",
    40,
    "/crops/icons/echinacea.avif",
    [],
  ],
  [
    "eggplant",
    "Eggplant",
    55,
    "/crops/icons/eggplant.avif",
    [],
  ],
  [
    "facing-heaven-pepper",
    "Facing Heaven Pepper",
    0,
    "/crops/icons/facing-heaven-pepper.avif",
    [],
  ],
  [
    "fatilii-pepper",
    "Fatilii Pepper",
    0,
    "/crops/icons/fatilii-pepper.avif",
    [],
  ],
  [
    "fava-bean",
    "Fava Bean",
    0,
    "/crops/icons/fava-bean.avif",
    [],
  ],
  [
    "fennel",
    "Fennel",
    40,
    "/crops/icons/fennel.avif",
    [],
  ],
  [
    "flower",
    "Flower",
    0,
    "/crops/icons/flower.avif",
    [],
  ],
  [
    "french-breakfast-radish",
    "French Breakfast Radish",
    15,
    "/crops/icons/french-breakfast-radish.avif",
    [],
  ],
  [
    "fresno-pepper",
    "Fresno Pepper",
    0,
    "/crops/icons/fresno-pepper.avif",
    [],
  ],
  [
    "fuji-apple",
    "Fuji Apple",
    360,
    "/crops/icons/fuji-apple.avif",
    [],
  ],
  [
    "gala-apple",
    "Gala Apple",
    300,
    "/crops/icons/gala-apple.avif",
    [],
  ],
  [
    "galangal",
    "Galangal",
    0,
    "/crops/icons/galangal.avif",
    [],
  ],
  [
    "garlic-chives",
    "Garlic Chives",
    8,
    "/crops/icons/garlic-chives.avif",
    [],
  ],
  [
    "garlic",
    "Garlic",
    0,
    "/crops/icons/garlic.avif",
    [],
  ],
  [
    "generic-plant",
    "Generic Plant",
    0,
    "/crops/icons/generic-plant.avif",
    [],
  ],
  [
    "german-chamomile",
    "German Chamomile",
    30,
    "/crops/icons/german-chamomile.avif",
    [],
  ],
  [
    "ghost-pepper",
    "Ghost Pepper",
    0,
    "/crops/icons/ghost-pepper.avif",
    [],
  ],
  [
    "ginger",
    "Ginger",
    25,
    "/crops/icons/ginger.avif",
    [],
  ],
  [
    "golden-beet",
    "Golden Beet",
    30,
    "/crops/icons/golden-beet.avif",
    [],
  ],
  [
    "golden-delicious-apple",
    "Golden Delicious Apple",
    450,
    "/crops/icons/golden-delicious-apple.avif",
    [],
  ],
  [
    "granny-smith-apple",
    "Granny Smith Apple",
    450,
    "/crops/icons/granny-smith-apple.avif",
    [],
  ],
  [
    "green-anjou-pear",
    "Green D'anjou Pear",
    300,
    "/crops/icons/green-anjou-pear.avif",
    [],
  ],
  [
    "green-bartlett-pear",
    "Green Bartlett Pear",
    85,
    "/crops/icons/green-bartlett-pear.avif",
    [],
  ],
  [
    "green-bell-pepper",
    "Green Bell Pepper",
    30,
    "/crops/icons/green-bell-pepper.avif",
    [],
  ],
  [
    "green-birds-eye-chili",
    "Green Bird's Eye Chili",
    0,
    "/crops/icons/green-birds-eye-chili.avif",
    [],
  ],
  [
    "green-cabbage",
    "Cabbage",
    50,
    "/crops/icons/green-cabbage.avif",
    [
      "blue-lake-bean",
    ],
  ],
  [
    "green-onion",
    "Green Onion",
    10,
    "/crops/icons/green-onion.avif",
    [],
  ],
  [
    "green-serrano-pepper",
    "Green Serrano Pepper",
    75,
    "/crops/icons/green-serrano-pepper.avif",
    [],
  ],
  [
    "green-tabasco-pepper",
    "Tabasco Pepper",
    70,
    "/crops/icons/green-tabasco-pepper.avif",
    [],
  ],
  [
    "green-zebra-tomato",
    "Green Zebra Tomato",
    45,
    "/crops/icons/green-zebra-tomato.avif",
    [],
  ],
  [
    "guajillo-pepper",
    "Guajillo Pepper",
    0,
    "/crops/icons/guajillo-pepper.avif",
    [],
  ],
  [
    "habanero-pepper",
    "Habanero Pepper",
    40,
    "/crops/icons/habanero-pepper.avif",
    [],
  ],
  [
    "hemp",
    "Hemp",
    450,
    "/crops/icons/hemp.avif",
    [],
  ],
  [
    "hillbilly-tomato",
    "Hillbilly Tomato",
    120,
    "/crops/icons/hillbilly-tomato.avif",
    [
      "borage",
      "carrot",
      "mint",
    ],
  ],
  [
    "honeydew-melon",
    "Honeydew Melon",
    150,
    "/crops/icons/honeydew-melon.avif",
    [],
  ],
  [
    "hop",
    "Common Hop",
    0,
    "/crops/icons/hop.avif",
    [],
  ],
  [
    "hungarian-wax-pepper",
    "Hungarian Wax Pepper",
    40,
    "/crops/icons/hungarian-wax-pepper.avif",
    [
      "parsley",
    ],
  ],
  [
    "iceberg-lettuce",
    "Iceberg Lettuce",
    15,
    "/crops/icons/iceberg-lettuce.avif",
    [],
  ],
  [
    "icicle-radish",
    "Icicle Radish",
    10,
    "/crops/icons/icicle-radish.avif",
    [],
  ],
  [
    "indigo",
    "Indigo",
    0,
    "/crops/icons/indigo.avif",
    [],
  ],
  [
    "jalapeno",
    "Jalapeno Pepper",
    45,
    "/crops/icons/jalapeno.avif",
    [],
  ],
  [
    "japanese-yam",
    "Japanese Yam",
    0,
    "/crops/icons/japanese-yam.avif",
    [],
  ],
  [
    "kabocha-squash",
    "Kabocha Squash",
    140,
    "/crops/icons/kabocha-squash.avif",
    [
      "borage",
      "corn",
    ],
  ],
  [
    "kohlrabi",
    "Kohlrabi",
    30,
    "/crops/icons/kohlrabi.avif",
    [
      "german-chamomile",
    ],
  ],
  [
    "lacinato-kale",
    "Lacinato Kale",
    75,
    "/crops/icons/lacinato-kale.avif",
    [
      "dill",
      "thyme",
    ],
  ],
  [
    "lavender",
    "Lavender",
    50,
    "/crops/icons/lavender.avif",
    [
      "purple-cauliflower",
    ],
  ],
  [
    "leek",
    "Leek",
    30,
    "/crops/icons/leek.avif",
    [
      "spinach",
    ],
  ],
  [
    "lemon-balm",
    "Lemon Balm",
    50,
    "/crops/icons/lemon-balm.avif",
    [
      "rosemary",
    ],
  ],
  [
    "lemon-drop-pepper",
    "Lemon Drop Pepper",
    0,
    "/crops/icons/lemon-drop-pepper.avif",
    [],
  ],
  [
    "lemon-verbena",
    "Lemon Verbena",
    120,
    "/crops/icons/lemon-verbena.avif",
    [],
  ],
  [
    "lemongrass",
    "Lemongrass",
    140,
    "/crops/icons/lemongrass.avif",
    [],
  ],
  [
    "lima-bean",
    "Lima Bean",
    25,
    "/crops/icons/lima-bean.avif",
    [],
  ],
  [
    "lions-mane-mushroom",
    "Lion's Mane",
    0,
    "/crops/icons/lions-mane-mushroom.avif",
    [],
  ],
  [
    "looseleaf-lettuce",
    "Looseleaf Lettuce",
    25,
    "/crops/icons/looseleaf-lettuce.avif",
    [],
  ],
  [
    "lovage",
    "Lovage",
    80,
    "/crops/icons/lovage.avif",
    [],
  ],
  [
    "madame-jeanette-pepper",
    "Madame Jeannette Pepper",
    0,
    "/crops/icons/madame-jeanette-pepper.avif",
    [],
  ],
  [
    "malagueta-pepper",
    "Malagueta Pepper",
    0,
    "/crops/icons/malagueta-pepper.avif",
    [],
  ],
  [
    "marjoram",
    "Marjoram",
    25,
    "/crops/icons/marjoram.avif",
    [],
  ],
  [
    "marshmallow",
    "Marshmallow",
    0,
    "/crops/icons/marshmallow.avif",
    [],
  ],
  [
    "medusa-pepper",
    "Medusa Pepper",
    0,
    "/crops/icons/medusa-pepper.avif",
    [],
  ],
  [
    "melon",
    "Melon",
    130,
    "/crops/icons/melon.avif",
    [],
  ],
  [
    "millet",
    "Millet",
    0,
    "/crops/icons/millet.avif",
    [],
  ],
  [
    "mint",
    "Mint",
    75,
    "/crops/icons/mint.avif",
    [
      "green-zebra-tomato",
    ],
  ],
  [
    "money-tree",
    "Money Tree",
    0,
    "/crops/icons/money-tree.avif",
    [],
  ],
  [
    "mugwort",
    "Mugwort",
    0,
    "/crops/icons/mugwort.avif",
    [],
  ],
  [
    "mushroom",
    "Mushroom",
    0,
    "/crops/icons/mushroom.avif",
    [],
  ],
  [
    "napa-cabbage",
    "Napa Cabbage",
    45,
    "/crops/icons/napa-cabbage.avif",
    [],
  ],
  [
    "nectarine",
    "Nectarine",
    365,
    "/crops/icons/nectarine.avif",
    [],
  ],
  [
    "oat",
    "Oat",
    7,
    "/crops/icons/oat.avif",
    [],
  ],
  [
    "okra",
    "Okra",
    25,
    "/crops/icons/okra.avif",
    [],
  ],
  [
    "onion-chive",
    "Onion Chive",
    8,
    "/crops/icons/onion-chive.avif",
    [
      "broccoli",
      "tomato",
      "strawberry",
      "eggplant",
      "parsley",
    ],
  ],
  [
    "orange-bell-pepper",
    "Orange Bell Pepper",
    30,
    "/crops/icons/orange-bell-pepper.avif",
    [],
  ],
  [
    "orange-scotch-bonnet",
    "Scotch Bonnet Pepper",
    0,
    "/crops/icons/orange-scotch-bonnet.avif",
    [],
  ],
  [
    "oregano",
    "Oregano",
    40,
    "/crops/icons/oregano.avif",
    [],
  ],
  [
    "ornamental-gourd",
    "Ornamental Gourds",
    0,
    "/crops/icons/ornamental-gourd.avif",
    [],
  ],
  [
    "parsley",
    "Parsley",
    10,
    "/crops/icons/parsley.avif",
    [],
  ],
  [
    "parsnip",
    "Parsnip",
    20,
    "/crops/icons/parsnip.avif",
    [],
  ],
  [
    "pattypan-squash",
    "Pattypan Squash",
    100,
    "/crops/icons/pattypan-squash.avif",
    [],
  ],
  [
    "peach",
    "Peach",
    365,
    "/crops/icons/peach.avif",
    [],
  ],
  [
    "peanut",
    "Peanut",
    30,
    "/crops/icons/peanut.avif",
    [
      "eggplant",
    ],
  ],
  [
    "peppadew-pepper",
    "Peppadew Pepper",
    0,
    "/crops/icons/peppadew-pepper.avif",
    [],
  ],
  [
    "pequin-pepper",
    "Pequin Pepper",
    0,
    "/crops/icons/pequin-pepper.avif",
    [],
  ],
  [
    "peter-pepper",
    "Peter Pepper",
    0,
    "/crops/icons/peter-pepper.avif",
    [],
  ],
  [
    "pimento-pepper",
    "Pimento Pepper",
    60,
    "/crops/icons/pimento-pepper.avif",
    [],
  ],
  [
    "pineapple-tomato",
    "Pineapple Tomato",
    45,
    "/crops/icons/pineapple-tomato.avif",
    [],
  ],
  [
    "pink-oyster-mushroom",
    "Pink Oyster Mushroom",
    0,
    "/crops/icons/pink-oyster-mushroom.avif",
    [],
  ],
  [
    "plantain",
    "Plantain",
    0,
    "/crops/icons/plantain.avif",
    [],
  ],
  [
    "plum",
    "Plum",
    500,
    "/crops/icons/plum.avif",
    [],
  ],
  [
    "poblano-pepper",
    "Poblano Pepper",
    40,
    "/crops/icons/poblano-pepper.avif",
    [],
  ],
  [
    "pointed-cabbage",
    "Pointed Cabbage",
    30,
    "/crops/icons/pointed-cabbage.avif",
    [
      "rosemary",
      "thyme",
    ],
  ],
  [
    "porcini-mushroom",
    "Porcini Mushroom",
    0,
    "/crops/icons/porcini-mushroom.avif",
    [],
  ],
  [
    "portabello-mushroom",
    "Portobello",
    0,
    "/crops/icons/portabello-mushroom.avif",
    [],
  ],
  [
    "psilocybin-mushroom",
    "Psilocybin",
    0,
    "/crops/icons/psilocybin-mushroom.avif",
    [],
  ],
  [
    "pumpkin",
    "Pumpkin",
    250,
    "/crops/icons/pumpkin.avif",
    [],
  ],
  [
    "purple-carrot",
    "Purple Carrot",
    8,
    "/crops/icons/purple-carrot.avif",
    [],
  ],
  [
    "purple-cauliflower",
    "Purple Cauliflower",
    65,
    "/crops/icons/purple-cauliflower.avif",
    [],
  ],
  [
    "purple-pod-bean",
    "Purple Pod Bean",
    35,
    "/crops/icons/purple-pod-bean.avif",
    [
      "corn",
      "eggplant",
    ],
  ],
  [
    "purple-potato",
    "Purple Potato",
    35,
    "/crops/icons/purple-potato.avif",
    [],
  ],
  [
    "radicchio",
    "Radicchio",
    10,
    "/crops/icons/radicchio.avif",
    [],
  ],
  [
    "rainbow-chard",
    "Rainbow Chard",
    20,
    "/crops/icons/rainbow-chard.avif",
    [],
  ],
  [
    "rainier-cherry",
    "Rainier Cherry",
    450,
    "/crops/icons/rainier-cherry.avif",
    [],
  ],
  [
    "raspberry",
    "Raspberry",
    75,
    "/crops/icons/raspberry.avif",
    [],
  ],
  [
    "red-anjou-pear",
    "Red D'anjou Pear",
    300,
    "/crops/icons/red-anjou-pear.avif",
    [],
  ],
  [
    "red-bartlett-pear",
    "Red Bartlett Pear",
    85,
    "/crops/icons/red-bartlett-pear.avif",
    [
      "german-chamomile",
    ],
  ],
  [
    "red-bell-pepper",
    "Red Bell Pepper",
    30,
    "/crops/icons/red-bell-pepper.avif",
    [],
  ],
  [
    "red-cabbage",
    "Red Cabbage",
    30,
    "/crops/icons/red-cabbage.avif",
    [],
  ],
  [
    "red-carrot",
    "Red Carrot",
    8,
    "/crops/icons/red-carrot.avif",
    [],
  ],
  [
    "red-chard",
    "Red Chard",
    20,
    "/crops/icons/red-chard.avif",
    [],
  ],
  [
    "red-curly-kale",
    "Red Curly Kale",
    0,
    "/crops/icons/red-curly-kale.avif",
    [],
  ],
  [
    "red-giant-mustard",
    "Red Giant Mustard",
    20,
    "/crops/icons/red-giant-mustard.avif",
    [
      "dill",
    ],
  ],
  [
    "red-gold-potato",
    "Red Potato",
    0,
    "/crops/icons/red-gold-potato.avif",
    [],
  ],
  [
    "red-kuri-squash",
    "Red Kuri Squash",
    210,
    "/crops/icons/red-kuri-squash.avif",
    [],
  ],
  [
    "red-onion",
    "Red Onion",
    13,
    "/crops/icons/red-onion.avif",
    [],
  ],
  [
    "red-pointed-cabbage",
    "Red Pointed Cabbage",
    30,
    "/crops/icons/red-pointed-cabbage.avif",
    [],
  ],
  [
    "red-russian-kale",
    "Red Russian Kale",
    30,
    "/crops/icons/red-russian-kale.avif",
    [],
  ],
  [
    "red-savina-pepper",
    "Red Savina Pepper",
    40,
    "/crops/icons/red-savina-pepper.avif",
    [
      "carrot",
    ],
  ],
  [
    "red-scotch-bonnet",
    "Red Scotch Bonnet Pepper",
    0,
    "/crops/icons/red-scotch-bonnet.avif",
    [],
  ],
  [
    "red-serrano-pepper",
    "Serrano Pepper",
    75,
    "/crops/icons/red-serrano-pepper.avif",
    [],
  ],
  [
    "red-tabasco-pepper",
    "Red Tabasco Peppers",
    70,
    "/crops/icons/red-tabasco-pepper.avif",
    [
      "eggplant",
    ],
  ],
  [
    "rice",
    "Rice",
    0,
    "/crops/icons/rice.avif",
    [],
  ],
  [
    "rocoto-pepper",
    "Rocoto Pepper",
    0,
    "/crops/icons/rocoto-pepper.avif",
    [],
  ],
  [
    "romaine-lettuce",
    "Romaine Lettuce",
    30,
    "/crops/icons/romaine-lettuce.avif",
    [],
  ],
  [
    "rosemary",
    "Rosemary",
    60,
    "/crops/icons/rosemary.avif",
    [
      "lemon-balm",
      "arugula",
    ],
  ],
  [
    "runner-bean",
    "Runner Bean",
    30,
    "/crops/icons/runner-bean.avif",
    [],
  ],
  [
    "russet-potato",
    "Potato",
    30,
    "/crops/icons/russet-potato.avif",
    [
      "marjoram",
    ],
  ],
  [
    "rutabaga",
    "Rutabaga",
    17,
    "/crops/icons/rutabaga.avif",
    [],
  ],
  [
    "rye",
    "Rye",
    25,
    "/crops/icons/rye.avif",
    [],
  ],
  [
    "sage",
    "Sage",
    50,
    "/crops/icons/sage.avif",
    [
      "bok-choy",
    ],
  ],
  [
    "salsify",
    "Salsify",
    0,
    "/crops/icons/salsify.avif",
    [],
  ],
  [
    "santa-fe-grande-pepper",
    "Santa Fe Grande Pepper",
    60,
    "/crops/icons/santa-fe-grande-pepper.avif",
    [
      "tomato",
      "eggplant",
      "parsley",
    ],
  ],
  [
    "savoy-cabbage",
    "Savoy Cabbage",
    30,
    "/crops/icons/savoy-cabbage.avif",
    [],
  ],
  [
    "shallot",
    "Shallot",
    15,
    "/crops/icons/shallot.avif",
    [],
  ],
  [
    "shiitake-mushroom",
    "Shiitake Mushroom",
    0,
    "/crops/icons/shiitake-mushroom.avif",
    [],
  ],
  [
    "shishito-pepper",
    "Shishito Pepper",
    0,
    "/crops/icons/shishito-pepper.avif",
    [],
  ],
  [
    "siling-labuyo-pepper",
    "Siling Labuyo Pepper",
    0,
    "/crops/icons/siling-labuyo-pepper.avif",
    [],
  ],
  [
    "snap-pea",
    "Snap Pea",
    20,
    "/crops/icons/snap-pea.avif",
    [],
  ],
  [
    "soybean",
    "Soybean",
    55,
    "/crops/icons/soybean.avif",
    [],
  ],
  [
    "spaghetti-squash",
    "Spaghetti Squash",
    30,
    "/crops/icons/spaghetti-squash.avif",
    [],
  ],
  [
    "spinach",
    "Spinach",
    20,
    "/crops/icons/spinach.avif",
    [],
  ],
  [
    "spring-onion",
    "Spring Onion",
    8,
    "/crops/icons/spring-onion.avif",
    [],
  ],
  [
    "st-johns-wort",
    "St. John's Wort",
    60,
    "/crops/icons/st-johns-wort.avif",
    [],
  ],
  [
    "stevia",
    "Stevia",
    60,
    "/crops/icons/stevia.avif",
    [],
  ],
  [
    "strawberry",
    "Strawberry",
    30,
    "/crops/icons/strawberry.avif",
    [],
  ],
  [
    "striped-cavern-tomato",
    "Striped Cavern Tomato",
    0,
    "/crops/icons/striped-cavern-tomato.avif",
    [],
  ],
  [
    "sugarcane",
    "Sugarcane",
    70,
    "/crops/icons/sugarcane.avif",
    [],
  ],
  [
    "sunflower",
    "Sunflower",
    60,
    "/crops/icons/sunflower.avif",
    [],
  ],
  [
    "sunray-tomato",
    "Sunray Tomato",
    30,
    "/crops/icons/sunray-tomato.avif",
    [],
  ],
  [
    "sweet-italian-pepper",
    "Italian Sweet Pepper",
    90,
    "/crops/icons/sweet-italian-pepper.avif",
    [
      "carrot",
    ],
  ],
  [
    "sweet-potato",
    "Sweet Potato",
    100,
    "/crops/icons/sweet-potato.avif",
    [
      "parsnip",
    ],
  ],
  [
    "swiss-chard",
    "Swiss Chard",
    20,
    "/crops/icons/swiss-chard.avif",
    [],
  ],
  [
    "taro",
    "Taro",
    0,
    "/crops/icons/taro.avif",
    [],
  ],
  [
    "thyme",
    "Thyme",
    30,
    "/crops/icons/thyme.avif",
    [
      "lacinato-kale",
      "red-pointed-cabbage",
    ],
  ],
  [
    "tomatillo",
    "Tomatillo",
    90,
    "/crops/icons/tomatillo.avif",
    [],
  ],
  [
    "tomato",
    "Tomato",
    45,
    "/crops/icons/tomato.avif",
    [],
  ],
  [
    "trinidad-moruga-scorpion-pepper",
    "Trinidad Moruga Scorpion Pepper",
    0,
    "/crops/icons/trinidad-moruga-scorpion-pepper.avif",
    [],
  ],
  [
    "trinidad-scorpion-butch-t-pepper",
    "Trinidad Scorpion 'butch T' Pepper",
    0,
    "/crops/icons/trinidad-scorpion-butch-t-pepper.avif",
    [],
  ],
  [
    "trumpet-mushroom",
    "Trumpet Mushroom",
    0,
    "/crops/icons/trumpet-mushroom.avif",
    [],
  ],
  [
    "tulsi",
    "Tulsi",
    40,
    "/crops/icons/tulsi.avif",
    [],
  ],
  [
    "turmeric",
    "Turmeric",
    0,
    "/crops/icons/turmeric.avif",
    [],
  ],
  [
    "turnip",
    "Turnip",
    30,
    "/crops/icons/turnip.avif",
    [],
  ],
  [
    "watercress",
    "Watercress",
    20,
    "/crops/icons/watercress.avif",
    [],
  ],
  [
    "watermelon-radish",
    "Watermelon Radish",
    8,
    "/crops/icons/watermelon-radish.avif",
    [],
  ],
  [
    "watermelon",
    "Watermelon",
    200,
    "/crops/icons/watermelon.avif",
    [],
  ],
  [
    "wax-bean",
    "Wax Bean",
    40,
    "/crops/icons/wax-bean.avif",
    [],
  ],
  [
    "wheat",
    "Wheat",
    0,
    "/crops/icons/wheat.avif",
    [],
  ],
  [
    "white-button-mushroom",
    "White Button Mushroom",
    0,
    "/crops/icons/white-button-mushroom.avif",
    [],
  ],
  [
    "white-carrot",
    "White Carrot",
    8,
    "/crops/icons/white-carrot.avif",
    [],
  ],
  [
    "white-onion",
    "White Onion",
    13,
    "/crops/icons/white-onion.avif",
    [],
  ],
  [
    "white-oyster-mushroom",
    "White Oyster Mushroom",
    0,
    "/crops/icons/white-oyster-mushroom.avif",
    [],
  ],
  [
    "wormwood",
    "Wormwood",
    0,
    "/crops/icons/wormwood.avif",
    [],
  ],
  [
    "yellow-bell-pepper",
    "Yellow Bell Pepper",
    30,
    "/crops/icons/yellow-bell-pepper.avif",
    [
      "tomato",
      "eggplant",
    ],
  ],
  [
    "yellow-carrot",
    "Yellow Carrot",
    8,
    "/crops/icons/yellow-carrot.avif",
    [],
  ],
  [
    "yellow-cauliflower",
    "Yellow Cauliflower",
    30,
    "/crops/icons/yellow-cauliflower.avif",
    [],
  ],
  [
    "yellow-onion",
    "Yellow Onion",
    13,
    "/crops/icons/yellow-onion.avif",
    [],
  ],
  [
    "yellow-oyster-mushroom",
    "Yellow Oyster",
    0,
    "/crops/icons/yellow-oyster-mushroom.avif",
    [],
  ],
  [
    "yellow-scotch-bonnet",
    "Yellow Scotch Bonnet Pepper",
    0,
    "/crops/icons/yellow-scotch-bonnet.avif",
    [],
  ],
  [
    "yellow-squash",
    "Squash",
    0,
    "/crops/icons/yellow-squash.avif",
    [],
  ],
  [
    "yukon-gold-potato",
    "Yukon Gold Potato",
    30,
    "/crops/icons/yukon-gold-potato.avif",
    [],
  ],
  [
    "zucchini",
    "Green Zucchini",
    100,
    "/crops/icons/zucchini.avif",
    [],
  ],
];

const ALIASED_SLUG_LOOKUP: Record<string, string> = {
  "lettuce": "looseleaf-lettuce",
  "lambs-lettuce": "looseleaf-lettuce",
  "salad-bowl-lettuce": "looseleaf-lettuce",
  "black-seeded-simpson-lettuce": "looseleaf-lettuce",
  "red-butterhead-lettuce": "looseleaf-lettuce",
  "lettuce-igloo": "looseleaf-lettuce",
  "lettuce-freedom-mix": "looseleaf-lettuce",
  "lechuga-crespa": "looseleaf-lettuce",
  "celtuce": "looseleaf-lettuce",
  "miners-lettuce-1": "looseleaf-lettuce",
  "onion": "white-onion",
  "onion-1": "white-onion",
  "onion-2": "white-onion",
  "onion-3": "white-onion",
  "onion-white-lisbon": "spring-onion",
  "radish": "cherry-belle-radish",
  "wild-radish": "cherry-belle-radish",
  "cabbage": "green-cabbage",
  "cabbage-1": "green-cabbage",
  "chinese-cabbage": "green-cabbage",
  "beet-detroit-dark-red-medium-top": "beet",
  "beets": "beet",
  "green-bean": "blue-lake-bean",
  "swiss-chard-3": "swiss-chard",
  "fordhook-giant-swiss-chard": "swiss-chard",
  "carrot-scarlet-nantes": "carrot",
  "rainbow-carrot": "carrot",
  "kale": "red-russian-kale",
  "kale-1": "red-russian-kale",
  "chives": "onion-chive",
  "cucumber-1": "cucumber",
  "wild-cucumber": "cucumber",
  "pea": "snap-pea",
  "sweet-basil": "basil",
  "thai-basil": "basil",
  "potato": "russet-potato",
  "curled-parsley": "parsley",
  "chili-pepper": "cayenne-pepper",
  "garlic-1": "garlic",
  "hardneck-garlic": "garlic",
  "elephant-garlic": "garlic",
  "jalapeno-pepper": "jalapeno",
  "blue-potato": "purple-potato",
  "bell-pepper": "red-bell-pepper",
  "daikon": "icicle-radish",
  "hemp-1": "hemp",
  "italian-oregano": "oregano",
  "greek-oregano": "oregano",
  "green-zucchini": "zucchini",
  "dill-1": "dill",
  "tiny-tim-tomato": "tomato",
  "cherry-tomato-husky-red": "cherry-tomato",
  "cress-1": "watercress",
  "shallot-1": "shallot",
  "pak-choy-bok-choy": "bok-choy",
  "kohlrabi-1": "kohlrabi",
  "asparagus-1": "asparagus"
};

export const DEFAULT_PLANT_RADIUS = 25;

export const CROP_SLUGS = CROP_ROWS.map(row => row[0]);

const CROP_METADATA: Record<string, CropMetadata> = Object.fromEntries(
  CROP_ROWS.map(([slug, name, spread, icon, companions]) => [
    slug,
    { name, spread, icon, companions },
  ]),
);

export const normalizeCropSlug = (slug: string | undefined): string =>
  (slug || "")
    .trim()
    .toLowerCase()
    .replace(/['’]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

const startCaseSlug = (slug: string) =>
  normalizeCropSlug(slug)
    .split("-")
    .filter(Boolean)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ") || "Generic Plant";

export const findCropMetadata = (slug: string | undefined): CropMetadata => {
  const normalizedSlug = normalizeCropSlug(slug);
  return CROP_METADATA[normalizedSlug] || {
    name: startCaseSlug(normalizedSlug),
    spread: 0,
    icon: GENERIC_PLANT_ICON,
    companions: [],
  };
};

export const findCropIcon = (slug: string | undefined): string => {
  const normalizedSlug = normalizeCropSlug(slug);
  const crop = findCropMetadata(normalizedSlug);
  if (crop.icon != GENERIC_PLANT_ICON) { return crop.icon; }
  const aliasCrop = CROP_METADATA[ALIASED_SLUG_LOOKUP[normalizedSlug]];
  return aliasCrop?.icon || GENERIC_PLANT_ICON;
};

export const verifiedCropSlug = (slug: string | undefined): string => {
  const normalizedSlug = normalizeCropSlug(slug);
  if (normalizedSlug == "random") {
    return CROP_SLUGS[Math.floor(Math.random() * CROP_SLUGS.length)] || "not-set";
  }
  return normalizedSlug || "not-set";
};
