import * as React from "react";
import { ToolBayFormProps } from "../interfaces";
import {
  Widget,
  WidgetBody,
  WidgetHeader,
  Col,
  Row,
  BlurableInput,
  SaveBtn,
  FBSelect
} from "../../ui/index";
import { t } from "i18next";
import {
  TaggedToolSlotPointer, getArrayStatus, SpecialStatus
} from "../../resources/tagged_resources";
import { edit, destroy, saveAll, init } from "../../api/crud";
import { ToolBayHeader } from "./toolbay_header";
import { ToolTips } from "../../constants";
import { Popover, Position } from "@blueprintjs/core";
import { SlotMenu } from "./toolbay_slot_menu";

export class ToolBayForm extends React.Component<ToolBayFormProps, {}> {

  emptyToolSlot = (): TaggedToolSlotPointer => {
    return {
      uuid: "ERROR: GENERATED BY REDUCER - SHOULD BE UNSEEN",
      kind: "Point",
      specialStatus: SpecialStatus.SAVED,
      body: {
        x: 0,
        y: 0,
        z: 0,
        radius: 25,
        pointer_type: "ToolSlot",
        meta: {},
        tool_id: undefined,
        name: "Tool Slot",
        pullout_direction: 0
      }
    };
  }

  render() {
    const { toggle, dispatch, toolSlots, botPosition } = this.props;
    const toolSlotStatus = getArrayStatus(toolSlots);
    return <div className={"toolbay-widget"}>
      <Widget>
        <WidgetHeader helpText={ToolTips.TOOLBAY_LIST} title={t("Tool Slots")}>
          <button
            className="gray fb-button"
            hidden={!!toolSlotStatus}
            onClick={() => { toggle(); }}>
            {t("Back")}
          </button>
          <SaveBtn
            status={toolSlotStatus}
            onClick={() => {
              dispatch(saveAll(toolSlots, () => { toggle(); }));
            }} />
          <button
            className="green fb-button"
            onClick={() => { dispatch(init(this.emptyToolSlot())); }}>
            <i className="fa fa-plus" />
          </button>
        </WidgetHeader>
        <WidgetBody>
          <ToolBayHeader />
          {this.props.getToolSlots().map(
            (slot: TaggedToolSlotPointer, index: number) => {
              const { x, y, z } = slot.body;
              return <Row key={index}>
                <Col xs={1}>
                  <Popover position={Position.BOTTOM_LEFT}>
                    <i className="fa fa-gear" />
                    <SlotMenu
                      dispatch={dispatch}
                      slot={slot}
                      botPosition={botPosition} />
                  </Popover>
                </Col>
                <Col xs={2}>
                  <BlurableInput
                    value={(x || 0).toString()}
                    onCommit={(e) => {
                      dispatch(edit(slot, { x: parseInt(e.currentTarget.value, 10) }));
                    }}
                    type="number" />
                </Col>
                <Col xs={2}>
                  <BlurableInput
                    value={(y || 0).toString()}
                    onCommit={(e) => {
                      dispatch(edit(slot, { y: parseInt(e.currentTarget.value, 10) }));
                    }}
                    type="number" />
                </Col>
                <Col xs={2}>
                  <BlurableInput
                    value={(z || 0).toString()}
                    onCommit={(e) => {
                      dispatch(edit(slot, { z: parseInt(e.currentTarget.value, 10) }));
                    }}
                    type="number" />
                </Col>
                <Col xs={4}>
                  <FBSelect
                    list={this.props.getToolOptions()}
                    selectedItem={this.props.getChosenToolOption(slot.uuid)}
                    allowEmpty={true}
                    onChange={this.props.changeToolSlot(slot,
                      this.props.dispatch)} />
                </Col>
                <Col xs={1}>
                  <button
                    className="red fb-button del-button"
                    onClick={() => dispatch(destroy(slot.uuid))}>
                    <i className="fa fa-times" />
                  </button>
                </Col>
              </Row>;
            })}
        </WidgetBody>
      </Widget>
    </div>;
  }
}
